spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cherishdev
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root1234

  session:
    jdbc:
      store-type: jdbc
      table-name: SPRING_SESSION
      initialize-schema: always
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    properties:
      hibernate:
        format_sql: true
        show-sql: true
logging:
  config:
logging.level:
  org.hibernate.SQL: debug

server:
  port: 8080
