spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:mem:cherish;MODE=MYSQL
    driverClassName: org.h2.Driver
    username: sa
    password:

  session:
    jdbc:
      store-type: jdbc
      table-name: SPRING_SESSION


  jpa:
    hibernate:
      ddl-auto: create
    database: h2
    properties:
      hibernate:
        format_sql: true
        show-sql: true
  h2:
    console:
      enabled: true
logging:
  config:
logging.level:
  org.hibernate.SQL: debug

server:
  port: 8080
