create table avatar
(
    active             TINYINT(1),
    avatar_id          bigint generated by default as identity,
    created_date       timestamp(6),
    last_modified_date timestamp(6),
    birth              varchar(255) not null,
    gender             varchar(255) not null check (gender in ('MALE', 'FEMALE')),
    name               varchar(255) not null,
    primary key (avatar_id)
);

create table account
(
    active             TINYINT(1),
    avatar_id          bigint,
    account_id         bigint generated by default as identity,
    created_date       timestamp(6),
    last_modified_date timestamp(6),
    platform           varchar(255) not null check (platform in ('KAKAO', 'APPLE')),
    primary key (account_id),
    foreign key (avatar_id) references avatar(avatar_id)
);



create table diary
(
    active             TINYINT(1),
    avatar_id          bigint,
    created_date       timestamp(6),
    diary_id           bigint generated by default as identity,
    last_modified_date timestamp(6),
    writing_date       timestamp(6) not null,
    content            varchar(255) not null,
    device_id          varchar(255) not null,
    device_type        varchar(255) not null,
    kind               varchar(255) check (kind in ('EMOTION', 'QUESTION', 'FREE')),
    title              varchar(255),
    primary key (diary_id),
    foreign key (avatar_id) references avatar(avatar_id)
);

create table session_token
(
    active              TINYINT(1),
    avatar_id           bigint,
    created_date        timestamp(6),
    expired_date        timestamp(6),
    session_token_id    bigint generated by default as identity,
    device_id           varchar(255),
    device_type         varchar(255),
    session_token_vaule varchar(255),
    primary key (session_token_id)
    foreign key (avatar_id) references avatar(avatar_id)
);

CREATE TABLE SPRING_SESSION
(
    PRIMARY_ID            CHAR(36) NOT NULL,
    SESSION_ID            CHAR(36) NOT NULL,
    CREATION_TIME         BIGINT   NOT NULL,
    LAST_ACCESS_TIME      BIGINT   NOT NULL,
    MAX_INACTIVE_INTERVAL INT      NOT NULL,
    EXPIRY_TIME           BIGINT   NOT NULL,
    PRINCIPAL_NAME        VARCHAR(100),
    CONSTRAINT SPRING_SESSION_PK PRIMARY KEY (PRIMARY_ID)
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC;

CREATE UNIQUE INDEX SPRING_SESSION_IX1 ON SPRING_SESSION (SESSION_ID);
CREATE INDEX SPRING_SESSION_IX2 ON SPRING_SESSION (EXPIRY_TIME);
CREATE INDEX SPRING_SESSION_IX3 ON SPRING_SESSION (PRINCIPAL_NAME);

CREATE TABLE SPRING_SESSION_ATTRIBUTES
(
    SESSION_PRIMARY_ID CHAR(36)     NOT NULL,
    ATTRIBUTE_NAME     VARCHAR(200) NOT NULL,
    ATTRIBUTE_BYTES    BLOB         NOT NULL,
    CONSTRAINT SPRING_SESSION_ATTRIBUTES_PK PRIMARY KEY (SESSION_PRIMARY_ID, ATTRIBUTE_NAME),
    CONSTRAINT SPRING_SESSION_ATTRIBUTES_FK FOREIGN KEY (SESSION_PRIMARY_ID) REFERENCES SPRING_SESSION (PRIMARY_ID) ON DELETE CASCADE
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC;


