# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "cicd" ]
  pull_request:
    branches: [ "cicd" ]

permissions:
  contents: read

jobs:
  configuration:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./cherish-config

    steps:
    - name: Set up actions
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.ACTION_TOKEN }}
        submodules: true
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: check-config
      run: ls
    - name: copy-config
      run: cp -r ./resources/ ../backend/src/resources/
    - name: cd
      run: cd ../backend/src/resources
    - name: change-working-directory
      working-directory: /backend/src/resources
    - name: ls
      run: ls
    
  build:
    defaults:
      run:
        working-directory: ./backend/src

    runs-on: ubuntu-latest

    steps:
    - name: Set up actions
      uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: ls
      run: ls
    - name: pwd
      run: pwd
    # - name: Grant execute permission for gradlew
    #   run: chmod +x ./gradlew
    # - name: Build with Gradle
    #   run: ./gradlew clean build
